spring:
  application:
    name: delivery-system
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: delivery
    password: delivery
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
