{
 "title": "Kafka & Kafka JVM",
 "tags": [
  "wiki",
  "kafka",
  "jvm"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Brokers",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 8 },
   "targets": [
    { "expr": "kafka_brokers" }
   ]
  },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 8 },
   "targets": [
    { "expr": "kafka_topics" }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(consumergroup, topic) (kafka_consumergroup_lag)"
    }
   ]
  },
  {
   "title": "Kafka JVM Heap Used (bytes)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "kafka_jvm_memory_heap_used_bytes"
    }
   ]
  },
  {
   "title": "Kafka JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "kafka_jvm_threads_threadcount" }
   ]
  }
 ]
}