{
 "title": "MySQL Metrics",
 "tags": [
  "wiki",
  "mysql"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Threads Connected",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected"
    }
   ]
  },
  {
   "title": "Queries/s",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions[1m])"
    }
   ]
  },
  {
   "title": "Slow Queries/s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries[5m])"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_buffer_pool_pages_data"
    }
   ]
  }
 ]
}