server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: payment-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

fault:
  delay-millis: 0
  fail: false

logging:
  level:
    com.example.payment: INFO
