service:
  member:
    url: http://closet-member:8081/api/v1
  product:
    url: http://closet-product:8082/api/v1
  order:
    url: http://closet-order:8083/api/v1
  payment:
    url: http://closet-payment:8084/api/v1
