server:
  port: 8085

spring:
  application:
    name: closet-bff
  threads:
    virtual:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

service:
  member:
    url: http://localhost:8081/api/v1
  product:
    url: http://localhost:8082/api/v1
  order:
    url: http://localhost:8083/api/v1
  payment:
    url: http://localhost:8084/api/v1
  search:
    url: http://localhost:8086
  review:
    url: http://localhost:8087
  shipping:
    url: http://localhost:8088
  inventory:
    url: http://localhost:8089
