server:
  port: 8080

spring:
  application:
    name: closet-gateway
  reactor:
    context-propagation: auto
  cloud:
    gateway:
      routes:
        - id: bff-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/**

jwt:
  secret: closet-member-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
