server:
  port: 9090

spring:
  application:
    name: closet-external-api
  datasource:
    url: jdbc:mysql://localhost:3306/closet_external?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.closet.external: DEBUG
    org.hibernate.SQL: DEBUG
